steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloudbuilddemo/mynodejsapplication', '-f', 'Dockerfile', '.']
    dir: "./nodeapp"
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloudbuilddemo/mynodejsapplication']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      - 'run'
      - 'deploy'
      - 'demo-app'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/cloudbuilddemo/mynodejsapplication'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY